=== richardRadli/Multi_Phase_Deep_Random_Neural_Network/config/json_files/FCNN_config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "FCNN Configuration",
  "type": "object",
  "properties": {
    "dataset_name": {
      "type": "string",
      "enum": [
        "adult",
        "cifar10",
        "connect4",
        "isolete",
        "letter",
        "mnist",
        "mnist_fashion",
        "musk2",
        "optdigits",
        "page_blocks",
        "satimages",
        "segment",
        "shuttle",
        "spambase",
        "usps",
        "wall",
        "waveform"
      ],
      "description": "The name of the dataset to be used."
    },
    "patience": {
      "type": "integer",
      "description": "The number of epochs after which the training should be stopped if the validation loss is not decreasing."
    },
    "seed": {
      "type": "boolean",
      "description": "Controls the way to generate random values. If set to True, the same values will be generated in every execution."
    },
    "optimizer": {
      "type": "string",
      "enum": ["adam", "sgd"],
      "description": "Desired optimizer to use."
    },
    "optimization": {
      "type": "object",
      "description": "Optimization configurations for different datasets.",
      "properties": {
        "adam": {
          "type": "object",
          "description": "Configuration for ADAM optimizer for different datasets.",
          "properties": {
            "learning_rate": {
              "type": "object",
              "description": "Learning rates for different datasets using ADAM.",
              "properties": {
                "adult": { "type": "number" },
                "cifar10": { "type": "number" },
                "connect4": { "type": "number" },
                "isolete": { "type": "number" },
                "letter": { "type": "number" },
                "mnist": { "type": "number" },
                "mnist_fashion": { "type": "number" },
                "musk2": { "type": "number" },
                "optdigits": { "type": "number" },
                "page_blocks": { "type": "number" },
                "satimages": { "type": "number" },
                "segment": { "type": "number" },
                "shuttle": { "type": "number" },
                "spambase": { "type": "number" },
                "usps": { "type": "number" },
                "wall": { "type": "number" },
                "waveform": { "type": "number" }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        },
        "sgd": {
          "type": "object",
          "description": "Configuration for SGD optimizer for different datasets.",
          "properties": {
            "learning_rate": {
              "type": "object",
              "description": "Learning rates for different datasets using SGD.",
              "properties": {
                "adult": { "type": "number" },
                "cifar10": { "type": "number" },
                "connect4": { "type": "number" },
                "isolete": { "type": "number" },
                "letter": { "type": "number" },
                "mnist": { "type": "number" },
                "mnist_fashion": { "type": "number" },
                "musk2": { "type": "number" },
                "optdigits": { "type": "number" },
                "page_blocks": { "type": "number" },
                "satimages": { "type": "number" },
                "segment": { "type": "number" },
                "shuttle": { "type": "number" },
                "spambase": { "type": "number" },
                "usps": { "type": "number" },
                "wall": { "type": "number" },
                "waveform": { "type": "number" }
              },
              "additionalProperties": false
            },
            "momentum": {
              "type": "object",
              "description": "Momentum values for different datasets using SGD.",
              "properties": {
                "adult": { "type": "number" },
                "cifar10": { "type": "number" },
                "connect4": { "type": "number" },
                "isolete": { "type": "number" },
                "letter": { "type": "number" },
                "mnist": { "type": "number" },
                "mnist_fashion": { "type": "number" },
                "musk2": { "type": "number" },
                "optdigits": { "type": "number" },
                "page_blocks": { "type": "number" },
                "satimages": { "type": "number" },
                "segment": { "type": "number" },
                "shuttle": { "type": "number" },
                "spambase": { "type": "number" },
                "usps": { "type": "number" },
                "wall": { "type": "number" },
                "waveform": { "type": "number" }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "hidden_neurons": {
      "type": "object",
      "description": "Number of hidden nodes in the hidden layers for different datasets.",
      "properties": {
        "adult": {
          "type": "integer"
        },
        "cifar10": {
          "type": "integer"
        },
        "connect4": {
          "type": "integer"
        },
        "isolete": {
          "type": "integer"
        },
        "letter": {
          "type": "integer"
        },
        "mnist": {
          "type": "integer"
        },
        "mnist_fashion": {
          "type": "integer"
        },
        "musk2": {
          "type": "integer"
        },
        "optdigits": {
          "type": "integer"
        },
        "page_blocks": {
          "type": "integer"
        },
        "satimages": {
          "type": "integer"
        },
        "segment": {
          "type": "integer"
        },
        "shuttle": {
          "type": "integer"
        },
        "spambase": {
          "type": "integer"
        },
        "usps": {
          "type": "integer"
        },
        "wall": {
          "type": "integer"
        },
        "waveform": {
          "type": "integer"
        }
      }
    },
    "batch_size": {
      "type": "object",
      "description": "Batch sizes for different datasets.",
      "properties": {
        "adult": {
          "type": "integer"
        },
        "cifar10": {
          "type": "integer"
        },
        "connect4": {
          "type": "integer"
        },
        "isolete": {
          "type": "integer"
        },
        "letter": {
          "type": "integer"
        },
        "mnist": {
          "type": "integer"
        },
        "mnist_fashion": {
          "type": "integer"
        },
        "musk2": {
          "type": "integer"
        },
        "optdigits": {
          "type": "integer"
        },
        "page_blocks": {
          "type": "integer"
        },
        "satimages": {
          "type": "integer"
        },
        "segment": {
          "type": "integer"
        },
        "shuttle": {
          "type": "integer"
        },
        "spambase": {
          "type": "integer"
        },
        "usps": {
          "type": "integer"
        },
        "wall": {
          "type": "integer"
        },
        "waveform": {
          "type": "integer"
        }
      }
    },
    "epochs": {
      "type": "integer",
      "description": "Number of epochs."
    },
    "num_tests": {
      "type": "integer",
      "description": "How many times a test should be repeated."
    },
    "device": {
      "type": "string",
      "enum": ["gpu", "cuda", "cpu"],
      "description": "The selected device where the computations will be executed."
    }
  },
  "required": ["dataset_name", "patience", "seed", "hidden_neurons", "batch_size", "epochs"]
}

=== richardRadli/Multi_Phase_Deep_Random_Neural_Network/config/json_files/FCNN_config.json
{
  "dataset_name": "wall",
  "patience": 10,
  "seed": false,
  "epochs": 1000,
  "device": "cuda",
  "num_tests": 10,
  "optimizer": "adam",
  "optimization": {
    "adam": {
      "learning_rate": {
        "adult": 0.001,
        "cifar10": 0.0005,
        "connect4": 0.0014840476104628093,
        "isolete": 0.001907640069101866,
        "letter": 0.000889053777822152,
        "mnist": 0.0005541711466489801,
        "mnist_fashion": 0.0005541711466489801,
        "musk2": 0.007645316148798358,
        "optdigits": 0.0004845929511061878,
        "page_blocks": 0.002273152099419009,
        "satimages": 0.0008633547703952462,
        "segment": 0.0009172205002756651,
        "shuttle": 0.0007259147473856188,
        "spambase": 0.0009002077236058769,
        "usps": 0.0010065774024284563,
        "wall": 0.0024484865064793807,
        "waveform": 0.0007079991167221878
      }
    },
    "sgd": {
      "learning_rate": {
        "adult": 0.01,
        "cifar10": 0.01,
        "connect4": 0.00108595,
        "isolete": 0.0333806,
        "letter": 0.09160847263704444,
        "mnist": 0.019882026603355512,
        "mnist_fashion": 0.00448498,
        "musk2": 0.0806255218079114,
        "optdigits": 0.07237220479573866,
        "page_blocks": 0.06974642599680506,
        "satimages": 0.07335846253628561,
        "segment": 0.010144021097474178,
        "shuttle": 0.025163419995939785,
        "spambase": 0.010401290366553876,
        "usps": 0.008074552694497727,
        "wall": 0,
        "waveform": 0
      },
      "momentum": {
        "adult": 0.9,
        "cifar10": 0.9,
        "connect4": 0.981549,
        "isolete": 0.876804,
        "letter": 0.7396715844501105,
        "mnist": 0.9684911819032582,
        "mnist_fashion": 0.663993,
        "musk2": 0.7478361175389169,
        "optdigits": 0.7748385889275364,
        "page_blocks": 0.5685224132160962,
        "satimages": 0.8969242048695005,
        "segment": 0.9787279039238386,
        "shuttle": 0.7951258472078417,
        "spambase": 0.5258957501732601,
        "usps": 0.9872259959152406,
        "wall": 0,
        "waveform": 0
      }
    }
  },
  "hidden_neurons": {
    "adult": 256,
    "cifar10": 2048,
    "connect4": 866,
    "isolete": 1300,
    "letter": 1500,
    "mnist": 2000,
    "mnist_fashion": 2000,
    "musk2": 866,
    "optdigits": 600,
    "page_blocks": 216,
    "satimages": 1200,
    "segment": 1000,
    "shuttle": 216,
    "spambase": 500,
    "usps": 1000,
    "wall": 866,
    "waveform": 500
  },
  "batch_size": {
    "adult": 64,
    "cifar10": 128,
    "connect4": 128,
    "isolete": 128,
    "letter": 64,
    "mnist": 128,
    "mnist_fashion": 128,
    "musk2": 64,
    "optdigits": 128,
    "page_blocks": 128,
    "satimages": 64,
    "segment": 128,
    "shuttle": 64,
    "spambase": 32,
    "usps": 64,
    "wall": 128,
    "waveform": 64
  }
}
