=== richardRadli/Multi_Phase_Deep_Random_Neural_Network/config/json_files/IPMPDRNN_config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Network Configuration",
  "type": "object",
  "properties": {
    "dataset_name": {
      "type": "string",
      "enum": [
        "adult",
        "cifar10",
        "connect4",
        "isolete",
        "letter",
        "mnist",
        "mnist_fashion",
        "musk2",
        "optdigits",
        "page_blocks",
        "satimages",
        "segment",
        "shuttle",
        "spambase",
        "usps",
        "wall",
        "waveform"
      ],
      "description": "The name of the dataset to be used."
    },
    "activation": {
      "type": "string",
      "enum": ["ReLU", "LeakyReLU", "Tanh", "Sigmoid", "Identity"],
      "description": "The activation function to be used in the neural network."
    },
    "number_of_tests": {
      "type": "integer",
      "description": "Number of tests to be performed."
    },
    "seed": {
      "type": "boolean",
      "description": "Controls the way to generate random values. If set to True, the same values will be generated in every execution."
    },
    "method": {
      "type": "string",
      "enum": ["BASE", "EXP_ORT", "EXP_ORT_C"],
      "description": "The method to generate new weights in consecutive layers."
    },
    "mu": {
      "type": "number",
      "description": "The mean of a uniform distribution is the midpoint of the interval."
    },
    "sigma": {
      "type": "number",
      "description": "The standard deviation of a uniform distribution is a measure of the spread of the distribution."
    },
    "num_aux_net": {
      "type": "integer",
      "description": "Number of aux networks to create."
    },
    "eq_neurons": {
      "type": "object",
      "description": "Number of equal neurons.",
      "properties": {
        "adult": {
          "type": "array"
        },
        "cifar10": {
          "type": "array"
        },
        "connect4": {
          "type": "array"
        },
        "isolete": {
          "type": "array"
        },
        "letter": {
          "type": "array"
        },
        "mnist": {
          "type": "array"
        },
        "mnist_fashion": {
          "type": "array"
        },
        "musk2": {
          "type": "array"
        },
        "optdigits": {
          "type": "array"
        },
        "page_blocks": {
          "type": "array"
        },
        "satimages": {
          "type": "array"
        },
        "segment": {
          "type": "array"
        },
        "shuttle": {
          "type": "array"
        },
        "spambase": {
          "type": "array"
        },
        "usps": {
          "type": "array"
        },
        "wall": {
          "type": "array"
        },
        "waveform": {
          "type": "array"
        }
      }
    },
    "exp_neurons": {
      "type": "object",
      "description": "Number of equal neurons.",
      "properties": {
        "adult": {
          "type": "array"
        },
        "cifar10": {
          "type": "array"
        },
        "connect4": {
          "type": "array"
        },
        "isolete": {
          "type": "array"
        },
        "letter": {
          "type": "array"
        },
        "mnist": {
          "type": "array"
        },
        "mnist_fashion": {
          "type": "array"
        },
        "musk2": {
          "type": "array"
        },
        "optdigits": {
          "type": "array"
        },
        "page_blocks": {
          "type": "array"
        },
        "satimages": {
          "type": "array"
        },
        "segment": {
          "type": "array"
        },
        "shuttle": {
          "type": "array"
        },
        "spambase": {
          "type": "array"
        },
        "usps": {
          "type": "array"
        },
        "wall": {
          "type": "array"
        },
        "waveform": {
          "type": "array"
        }
      }
    },
    "subset_percentage": {
      "type": "object",
      "description": "Percentage of how much of the weights should be substituted.",
      "properties": {
        "adult": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "cifar10": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "connect4": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "isolete": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "letter": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "mnist": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "mnist_fashion": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "musk2": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "optdigits": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "page_blocks": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "satimages": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "segment": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "shuttle": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "spambase": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "usps": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "wall": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "waveform": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        }
      }
    },
    "rcond": {
      "type": "object",
      "description": "Value of the rcond parameter for the Moore-Penrose pseudo Inverse solver.",
      "properties": {
        "adult": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "cifar10": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "connect4": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "isolete": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "letter": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "mnist": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "mnist_fashion": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "musk2": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "optdigits": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "page_blocks": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "satimages": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "segment": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "shuttle": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "spambase": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "usps": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "wall": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        },
        "waveform": {
          "properties": {
            "BASE": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            },
            "EXP_ORT_C": {
              "oneOf": [
                { "type": "number" },
                { "type": "null" }
              ]
            }
          }
        }
      }
    },
    "penalty": {
      "type": "object",
      "description": "Value of the L2 penalty term.",
      "properties": {
        "adult": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "cifar10": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "connect4": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "isolete": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "letter": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "mnist": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "mnist_fashion": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "musk2": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "optdigits": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "page_blocks": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "satimages": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "segment": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "shuttle": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "spambase": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "usps": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "wall": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        },
        "waveform": {
          "oneOf": [
            { "type": "number" },
            { "type": "null" }
          ]
        }
      }
    }
  },
  "required": ["dataset_name", "activation", "number_of_tests", "seed", "subset_percentage", "method"]
}

=== richardRadli/Multi_Phase_Deep_Random_Neural_Network/config/json_files/IPMPDRNN_config.json
{
  "dataset_name": "page_blocks",
  "activation": "LeakyReLU",
  "number_of_tests": 20,
  "seed": true,
  "method": "EXP_ORT_C",
  "mu": 0,
  "sigma": 0.15,
  "num_aux_net": 4,
  "eq_neurons": {
    "adult": [300, 300, 300],
    "cifar10": [2000, 2000, 2000],
    "connect4": [866, 866, 866],
    "isolete": [1300, 1300, 1300],
    "letter": [1500, 1500, 1500],
    "mnist": [2000, 2000, 2000],
    "mnist_fashion": [2000, 2000, 2000],
    "musk2": [866, 866, 866],
    "optdigits": [216, 216, 216],
    "page_blocks": [216, 216, 216],
    "satimages": [600, 600, 600],
    "segment": [300, 300, 300],
    "shuttle": [216, 216, 216],
    "spambase": [400, 50, 50],
    "usps": [1000, 1000, 1000],
    "wall": [216, 216, 216],
    "waveform": [216, 216, 216]
  },
  "exp_neurons": {
    "adult": [600, 200, 100],
    "cifar10": [4000, 1500, 500],
    "connect4": [2049, 452, 100],
    "isolete": [1400, 1300, 1200],
    "letter": [3000, 1000, 500],
    "mnist": [8000, 5000, 3000],
    "mnist_fashion": [4000, 1500, 500],
    "musk2": [1200, 750, 650],
    "optdigits": [500, 200, 100],
    "page_blocks": [400, 200, 100],
    "satimages": [2600, 700, 300],
    "segment": [600, 200, 100],
    "shuttle": [400, 200, 50],
    "spambase": [800, 400, 300],
    "usps": [1600, 1000, 400],
    "wall": [600, 400, 300],
    "waveform": [700, 400, 100]
  },
  "subset_percentage": {
    "adult": 0.5,
    "cifar10": 0.1,
    "connect4": 0.5,
    "isolete": 0.55,
    "letter": 0.1,
    "mnist": 0.05,
    "mnist_fashion": 0.05,
    "musk2": 0.6,
    "optdigits": 0.4,
    "page_blocks": 0.5739251672543924,
    "satimages": 0.3,
    "segment": 0.4,
    "shuttle": 0.45,
    "spambase": 0.65,
    "usps": 0.4,
    "wall": 0.2,
    "waveform": 0.8285131061826998
  },
  "rcond": {
    "adult": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-15
    },
    "cifar10": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-15
    },
    "connect4": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-15,
      "EXP_ORT_C": 1e-15
    },
    "isolete": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 1e-15
    },
    "letter": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-15
    },
    "mnist": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-30
    },
    "mnist_fashion": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-30
    },
    "musk2": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 1e-15
    },
    "optdigits": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-5
    },
    "page_blocks": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1.717895413695424e-21
    },
    "satimages": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 1e-20
    },
    "segment": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 1e-15
    },
    "shuttle": {
      "BASE": 1e-5,
      "EXP_ORT": 1e-5,
      "EXP_ORT_C": 1e-15
    },
    "spambase": {
      "BASE": 1e-15,
      "EXP_ORT": 1e-15,
      "EXP_ORT_C": 1e-15
    },
    "usps": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 1e-15
    },
    "wall": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 3.046425256163358e-13
    },
    "waveform": {
      "BASE": null,
      "EXP_ORT": null,
      "EXP_ORT_C": 2.5925474137582335e-05
    }
  },
  "penalty": {
    "adult": 5,
    "cifar10": 0.15,
    "connect4": 5,
    "isolete": 5,
    "letter": 0.15,
    "mnist": 0.15,
    "mnist_fashion": 0.15,
    "musk2": 0.8,
    "optdigits": 8,
    "page_blocks": 11.609226861754372,
    "satimages": 8,
    "segment": 9,
    "shuttle": 8,
    "spambase": 0.15,
    "usps": 0.15,
    "wall": 28.262272871972648,
    "waveform": 2.6760824953901827
  }
}
